# Generated by Django 4.1.5 on 2023-03-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_avatar',
            field=models.ImageField(default='media/default/profile_avatar.png', upload_to='media/profiles'),
        ),
    ]
