# Generated by Django 4.1.5 on 2024-01-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("1", "Administrator"), ("2", "Doctor"), ("3", "Patient")],
                default="3",
                max_length=1,
            ),
        ),
    ]
