# Generated by Django 4.1.5 on 2024-01-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_rename_notes_appointment_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visit_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='visit_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
