# Generated by Django 4.1.5 on 2024-01-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_appointment_visit_price_doctor_visit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
