# Generated by Django 4.1.5 on 2024-01-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0005_appointment_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="confirmation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Canceled", "Canceled"),
                    ("Completed", "Completed"),
                ],
                default="Confirmed",
                max_length=50,
                null=True,
            ),
        ),
    ]
