# Generated by Django 4.1.5 on 2024-01-24 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_rename_test_results_medicaltest_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaltestimage',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='medical_test_images/')),
                ('medical_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_image', to='doctors.medicaltest')),
                ('medical_test_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_test_image', to='doctors.medicaltestimage')),
            ],
        ),
        migrations.AddField(
            model_name='medicaltestimage',
            name='images',
            field=models.ManyToManyField(related_name='medical_test_images', to='doctors.image'),
        ),
    ]
