# Generated by Django 4.1.5 on 2024-01-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_remove_medicaltestimage_image_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaltestimage',
            name='images',
        ),
        migrations.AddField(
            model_name='medicaltestimage',
            name='image',
            field=models.ImageField(default=1, upload_to='medical_test_images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
